
language: java

#sudo: required

#env: MAVEN_OPTS="-Xmx2G -XX:MaxPermSize=512M"

env:
  MAVEN_SKIP_RC=true
  MAVEN_OPTS="-Xmx2g -XX:MaxPermSize=512M"

# workaround added: https://github.com/travis-ci/travis-ci/issues/4629
before_install:
  - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml

cache:
  directories:
  - .autoconf
  - $HOME/.m2

jdk:
  - oraclejdk8

script:
  - mvn -B test -T4

